# Generated by Django 5.2.6 on 2025-10-08 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tourist_profiles/')),
                ('address', models.TextField(blank=True)),
                ('travel_style', models.CharField(blank=True, choices=[('ADVENTURE', 'Adventure Seeker'), ('LUXURY', 'Luxury Traveler'), ('BUDGET', 'Budget Backpacker'), ('FAMILY', 'Family Traveler'), ('SOLO', 'Solo Traveler'), ('CULTURAL', 'Cultural Explorer')], max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tourist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
