# Generated by Django 5.1.6 on 2025-10-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='image',
            new_name='extra_image1',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='location',
        ),
        migrations.AddField(
            model_name='destination',
            name='best_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='extra_image2',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='extra_image3',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='extra_image4',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='extra_image5',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='extra_image6',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
