# Generated by Django 5.2.6 on 2025-10-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_remove_tour_tourist_tour_notes_tour_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
