# Generated by Django 5.2.6 on 2025-10-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_earning_description_tourrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='guides/avatars/'),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
