# Generated by Django 5.2.6 on 2025-10-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_guideprofile_avatar_guideprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideprofile',
            name='linkedin',
        ),
    ]
