# Generated by Django 5.2.6 on 2025-10-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0007_remove_guideprofile_linkedin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourrequest',
            options={'verbose_name': 'Tour Request', 'verbose_name_plural': 'Tour Requests'},
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='duration_hours',
            field=models.PositiveIntegerField(choices=[(2, '2 hours (Quick tour)'), (4, '4 hours (Half day)'), (8, '8 hours (Full day)'), (12, '12 hours (Full day+)')], default=4, verbose_name='Tour Duration'),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='number_of_travelers',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Travelers'),
        ),
        migrations.AddField(
            model_name='tourrequest',
            name='places_to_explore',
            field=models.CharField(blank=True, help_text='Specific places the tourist wants to visit', max_length=500, verbose_name='Places to Explore'),
        ),
    ]
