# Generated by Django 5.2.7 on 2025-10-21 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_area_hotel_average_rating_hotel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Main image for hotel cards and listings', null=True, upload_to='hotel_profile_images/'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_image',
            field=models.ImageField(blank=True, help_text='Image for this room type', null=True, upload_to='room_images/'),
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='hotels.hotel')),
            ],
        ),
    ]
