# Generated by Django 5.2.7 on 2025-10-21 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_profile_image_roomtype_room_image_hotelimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hotelreview',
            unique_together={('hotel', 'tourist')},
        ),
        migrations.AddField(
            model_name='hotelreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hotelreview',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='hotels.hotelbooking'),
        ),
    ]
