# Generated by Django 5.2.7 on 2025-10-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotelreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreview',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
