# Generated by Django 5.2.6 on 2025-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
    ]
